### ISSUE TITLE
libzbar unhandled error windows

### ISSUE THREAD

**Issue by rpm5099** [rpm5099/mfawesome#10]
```python
(py3118) PS C:\Users\rob\Desktop\gitrepos\notes_and_utils> mfa
Traceback (most recent call last):
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\zbar_library.py", line 58, in load
    dependencies, libzbar = load_objects(Path(''))
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\zbar_library.py", line 50, in load_objects
    deps = [
           ^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\zbar_library.py", line 51, in <listcomp>
    cdll.LoadLibrary(str(directory.joinpath(dep)))
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Scripts\mfa.exe\__main__.py", line 4, in <module>
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\mfawesome\__init__.py", line 35, in <module>
    from . import config, exception, exec_mfawesome, logutils, mfa_secrets, ntptime, qrcodes, totp, utils
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\mfawesome\config.py", line 32, in <module>
    from mfawesome.qrcodes import ImportFromQRImage  # , Init_Otpauth_Migration, ScanQRDir
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\mfawesome\qrcodes.py", line 52, in <module>
    from qreader import QReader
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\qreader.py", line 21, in <module>
    from pyzbar.pyzbar import Decoded, ZBarSymbol
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
                   ^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
                             ^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\zbar_library.py", line 60, in load
    dependencies, libzbar = load_objects(Path(__file__).parent)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\zbar_library.py", line 54, in load_objects
    libzbar = cdll.LoadLibrary(str(directory.joinpath(fname)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob\.local\share\mamba\envs\py3118\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\rob\.local\share\mamba\envs\py3118\Lib\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by rpm5099** [comment]
Missing this:

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
